package com.app.enums;

public enum SubViewType {
    //ADMIN MENU
    A_TEACHER_VIEW, A_GROUP_VIEW, A_STUDENT_VIEW, A_SUBJECTS_VIEW, A_PLAN_VIEW,

    //TEACHER MENU
    T_TIMETABLE_VIEW, T_GROUP_VIEW, T_STUDENT_VIEW

}
